### ISSUE TITLE
Git checkout error [2022-01-08]

### ISSUE THREAD

**Issue by ghost** [Daniel-Abrecht/dpa-image-builder#1]
```
Cloning into '/home/anonymous/dpa-image-builder/build/repo/linux'...
done.
+ cd /home/anonymous/dpa-image-builder/build/repo/linux
+ git checkout c6fda0a09217b8c183cf1ef4782746fcfcf055f1
fatal: reference is not a tree: c6fda0a09217b8c183cf1ef4782746fcfcf055f1
+ cleanup
+ umount /home/anonymous/dpa-image-builder/build/repo/
make[1]: *** [makefile:23: bin/.done] Error 128
make[1]: Leaving directory '/home/anonymous/dpa-image-builder/kernel'
make: *** [makefile:30: kernel/bin/linux-image.deb] Error 2
```

*(otherwise I wanted to tell you that I really like your work ^^)*

**Comment by Daniel-Abrecht** [comment]
Thanks, it should be fixed now. I used a specific commit for the kernel since the newest used to cause me a few problems with the display, but it seams that commit wasn't available anymore in the remote repo. Anyway, it seams the current kernel version works once again, so I've changed it back to use the newest one now.
